// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omsuqhapewxznyohnmxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tc3VxaGFwZXd4em55b2hubXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjAwODksImV4cCI6MjA1ODI5NjA4OX0.VVyKLwo29i1ZgEF8CAiOfWmVRwRzuMgmsrBxM0IwOiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);